# Generated by Django 4.1.4 on 2022-12-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
